import time
from core.engine import Engine

class Launcher:
    def __init__(self):
        self.engine = Engine()
        print("Bot initialized...")

    def start(self):
        print("Bot starting up...")
        self.engine.load_urls([
            "https://tcr-therapies-summit.com/",
            "https://mrna-processmanufacturing.com/",
            "https://cell-therapy-analytics-europe.com/",
            "https://genetherapy-ophthalmology.com/",
            "https://lnp-characterization-analytical-development.com/",
            "https://genetherapy-immunogenicity.com/",
            "https://car-tcr-summit.com/",
            "https://inner-ear-disorders-therapeutics.com/",
            "https://lipid-nanoparticle-delivery-summit.com/",
            "https://mrnabased-therapeutics.com/",
            "https://gamma-delta-t-therapies-summit.com/",
            "https://in-vivo-engineering.com/",
            "https://process-development-celltx.com/",
            "https://peptide-based-therapeutics-summit.com/",
            "https://cdx-europe.com/",
            "https://lnp-formulation-process-development-pharma.com/",
            "https://genetherapy-conference.com/",
            "https://immuno-oncologyeurope.com/",
            "https://genetherapy-patient-engagement.com/",
            "https://mrna-quality-control.com/",
            "https://genetherapy-neurological-europe.com/",
            "https://cell-therapy-potency-assay.com/",
            "https://allogeneic-cell-therapies.com/",
            "https://ipsc-manufacturing-summit.com/",
            "https://genetherapy-analytical-europe.com/",
            "https://mrna-processmanufacturing-europe.com/",
            "https://genetherapy-comparability.com/",
            "https://supply-cell-immunotherapy.com/",
            "https://cartcr-europe.com/",
            "https://mrna-analytical-development.com/",
            "https://allogeneic-cell-therapies-europe.com/",
            "https://mrnabased-therapeutics-europe.com/",
            "https://cell-therapy-analytics.com/",
            "https://synthetic-biology-therapeutics-summit.com/",
            "https://dry-amd-therapeutics.com/",
            "https://crispr-conference.com/",
            "https://innate-killer-europe.com/",
            "https://macrophage-directed-therapies.com/",
            "https://b-and-t-cell-for-autoimmune.com/",
            "https://optimizing-aav-safety.com/",
            "https://innerear-disorders-therapeutics.com/",
            "https://multi-functional-cell-therapies.com/",
            "https://nasal-formulation-delivery.com/",
            "https://novel-conjugates.com/",
            "https://treg-directed-therapies.com/",
            "https://lab-asset-facility-europe.com/",
            "https://alzheimers-parkinsons-summit.com/",
            "https://wet-amd-drug-development.com/",
            "https://supply-chain-logistics-cgt.com/",
            "https://worldadc-europe.com/",
            "https://innatekiller.com/",
            "https://neuroimmunology-drugdevelopment.com/",
            "https://continuous-processing-pharma.com/",
            "https://fermentation-enabled-proteins.com/",
            "https://viral-vector-process-development.com/",
            "https://leaphr-lifesciences-europe.com/",
            "https://lbx-summit.com/",
            "https://glioblastoma-drugdevelopment.com/",
            "https://cns-proteindegradation.com/",
            "https://proteomic-drug-discovery.com/",
            "https://kinase-drug-discovery-summit.com/",
            "https://crispr-agbio-congress.com/",
            "https://ophthalmic-drug-delivery.com/",
            "https://microbiome-europe.com/",
            "https://ddr-inhibitors-summit.com/",
            "https://spatial-biology-immuno-oncology.com/",
            "https://tumor-models-sf.com/",
            "https://molecular-glue-summit.com/",
            "https://rnaibased-therapeutics.com/",
            "https://adc-targetselection.com/",
            "https://applied-biocatalysis.com/",
            "https://process-analytical-technology.com/",
            "https://covalent-drug-discovery.com/",
            "https://rna-drugdiscovery.com/",
            "https://capital-project-engineering.com/",
            "https://targeted-radiopharma.com/",
            "https://claudin-targeted-therapies-summit.com/",
            "https://cns-drug-delivery-summit.com/",
            "https://genome-editing-therapeutics-summit.com/",
            "https://tumour-models.com/",
            "https://personalized-cancer-vaccines.com/",
            "https://cell-therapy-autoimmune-disease.com/",
            "https://donor-selection-cell-source-summit.com/",
            "https://gpcrs-europe.com/",
            "https://genetherapy-cns.com/",
            "https://liquid-biopsy-surveillance-summit.com/",
            "https://leaphr-emerging-biopharma.com/",
            "https://worldadc-usa.com/",
            "https://tpd-europe.com/",
            "https://proteindegradation.com/",
            "https://leapta-lifesciences.com/",
            "https://fluid-imaging-biomarkers-neuro.com/",
            "https://spatialbiology-drugdevelopment.com/",
            "https://ipsc-therapies-summit.com/",
            "https://targeted-radiopharma-manuf-supply.com/",
            "https://neuropsychiatric-drug-development.com/",
            "https://ras-drugdevelopment.com/",
            "https://lipid-nanoparticle-development-europe.com/",
            "https://adc-process-development.com/",
            "https://crispr-analytical-development.com/",
            "https://mrna-processandmanufacturing.com/",
            "https://exosomebased-therapeutics.com/",
            "https://world-cdx.com/",
            "https://bispecific.com/",
            "https://oligos-cmc-analytical-development.com/",
            "https://adc-linker-conjugation.com/",
            "https://leap-hr-lifesciences-east.com/",
            "https://targeted-radiopharma-us2.com/",
            "https://gamma-delta-t-therapies.com/",
            "https://adc-toxicity.com/",
            "https://induced-proximity-summit.com/",
            "https://tumor-models.com/",
            "https://genetherapy-potency-assay.com/",
            "https://microbiome-summit.com/",
            "https://oligonucleotides-cns.com/",
            "https://cell-gene-pricing-reimbursement.com/",
            "https://worldadc-asia.com/",
            "https://hpapi-summit.com/",
            "https://rnaediting-summit.com/",
            "https://next-gen-genetherapy-vectors.com/",
            "https://tumor-myeloid-therapeutics.com/",
            "https://advancing-life-science-construction.com/",
            "https://computational-rna-design-delivery.com/",
            "https://lab-ops-for-biopharma.com/",
            "https://leaphr-healthcare.com/",
            "https://cytokine-immunotherapies.com/",
            "https://cell-engager-summit.com/",
            "https://adc-payload-summit.com/",
            "https://als-drug-development.com/",
            "https://3d-tissuemodels.com/",
            "https://glp-1-based-therapeutics.com/",
            "https://advanced-procurement-in-pharma.com/",
            "https://next-gen-rna.com/",
            "https://neoantigen-summit.com/",
            "https://mrna-processandmanufacturing-europe.com/",
            "https://adc-analytical.com/",
            "https://genetherapy-muscular.com/",
            "https://dermatology-drugdevelopment-europe.com/",
            "https://translational-digital-pathology-ai.com/",
            "https://cell-therapy-supply-chain-logistics.com/",
            "https://precision-medicine-in-ibd.com/",
            "https://innate-killer.com/",
            "https://gpcrs-drugdiscovery.com/",
            "https://microbiome-agbiotech.com/",
            "https://as-immunetolerance.com/",
            "https://genetherapy-analytical.com/",
            "https://genetherapy-neurological.com/",
            "https://til-therapies.com/",
            "https://genetherapy-europe.com/",
            
            
            
            
            
            
            
            "https://informaconnect.com/bioprocessinternational/speakers/",
            "https://www.bioprocessingsummit.com/Streams/Cell-Therapy",
            "https://www.pegsummit.com/",
            "https://www.pegsummit.com/In-vivo-engineering",
            "https://www.pegsummit.com/cell-based-immunotherapies#2",
            "https://www.immuno-oncologyeurope.com/",
            "https://allogeneic-cell-therapies-europe.com/",
            "https://www.discoveryontarget.com/",
            "https://www.pegsummit.com/",
            "https://informaconnect.com/bpieurope/speakers/",
            "https://www.immunogenicitysummit.com/22/immunogenicity-prediction",
            "https://www.immunogenicitysummit.com/22/bioassays-for-biologics",
            "https://www.immunogenicitysummit.com/22/immunogenicity-assessment-Clinical-Relevance",
            "https://www.immunogenicitysummit.com/22/Immunology-for-Biotherapeutics",
            "http://web.archive.org/web/20220711180806/https://informaconnect.com/bioprocessinternational/speakers/",
            "https://www.bioprocessingsummit.com/22/cell-culture",
            "https://www.bioprocessingsummit.com/22/bioproduction",
            "https://www.bioprocessingsummit.com/22/continuous-processing",
            "https://www.bioprocessingsummit.com/22/purification-and-recovery",
            "https://www.bioprocessingsummit.com/22/gene-therapy-cmc",
            "https://www.bioprocessingsummit.com/22/gene-therapy-manufacturing",
            "https://www.bioprocessingsummit.com/22/cell-therapy-cmc",
            "https://www.bioprocessingsummit.com/22/host-cell-proteins",
            "https://www.bioprocessingsummit.com/22/preclinical-analytical-development",
            "https://www.bioprocessingsummit.com/22/stability-biologics",
            "https://www.bioprocessingsummit.com/22/formulation-and-delivery-of-biologics",
            "https://www.bioprocessingsummit.com/22/vaccine-manufacturing",
            "https://www.immunogenicitysummit.com/21/immunogenicity-prediction",
            "https://www.immunogenicitysummit.com/21/Bioassays-for-Biologics",
            "https://www.immunogenicitysummit.com/21/Immunogenicity-Assessment-Clinical-Relevance",
            "https://www.immunogenicitysummit.com/21/Immunology-for-Biotherapeutics",
            "http://web.archive.org/web/20210619002826/https://informaconnect.com/bioprocessinternational/speakers/",
            "http://web.archive.org/web/20220119235400/https://informaconnect.com/bpieurope/speakers/",
            "https://www.bioprocessingeurope.com/21/cell-culture#Day2",
            "https://www.bioprocessingeurope.com/21/continuous-processing",
            "https://www.bioprocessingeurope.com/21/analytical-characterisation",
            "https://www.immunogenicitysummit.com/20/Immunogenicity-Assessment-Clinical-Relevance",
            "https://www.immunogenicitysummit.com/20/immunogenicity-prediction",
            "https://www.immunogenicitysummit.com/20/Bioassays-for-Biologics",
            "http://web.archive.org/web/20200806181949/https://informaconnect.com/bioprocessinternational/speakers/",
            "https://www.bioprocessingeurope.com/20/cell-culture",
            "https://www.bioprocessingeurope.com/20/cell-line-development",
            "https://www.bioprocessingeurope.com/20/continuous-processing",
            "https://www.bioprocessingeurope.com/20/purification",
            "https://www.bioprocessingeurope.com/20/cell-therapy",
            "https://www.bioprocessingeurope.com/20/gene-therapy",
            "https://www.bioprocessingeurope.com/20/analytical-characterisation",
            "https://www.bioprocessingeurope.com/20/formulation",
            "http://web.archive.org/web/20210302033734/https://informaconnect.com/bpieurope/speakers/",
            "https://www.immunogenicitysummit.com/19/Immunogenicity-Assessment-Clinical-Relevance",
            "https://www.immunogenicitysummit.com/19/immunogenicity-prediction",
            "https://www.immunogenicitysummit.com/19/Bioassays-for-Biologics",
            "https://www.immunogenicitysummit.com/19/Training-Immunology-for-Biotechnology",
            "https://www.immunogenicitysummit.com/18/Immunogenicity-Assessment-Clinical-Relevance",
            "https://www.immunogenicitysummit.com/18/immunogenicity-prediction",
            "https://www.immunogenicitysummit.com/18/Bioassays-for-Biologics",
            "https://www.immunogenicitysummit.com/18/Training-Immunology-for-Biotechnology"
        ])

        self.engine.run()
        print("Bot finished!")

    def stop(self):
        print("Bot stopped!")

if __name__ == "__main__":
    bot = Launcher()
    bot.start()
